name: Update Miles Sales

on:
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:

jobs:
  update-sales:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Python Script
        run: |
          python update_sales.py

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add sales.json
          git commit -m "Auto update sales" || echo "No changes"

      - name: Push
        run: |
          git pull --rebase
          git push
